# email_server.py
"""
Email Server Backend

Handles email sending requests from the interactive HTML report.
PDF generation is handled CLIENT-SIDE (browser print).
Server only sends JSON attachment (and metadata).
"""

from flask import Flask, request, jsonify
from flask_cors import CORS
from optional_email import send_report_email
import json
import os
from datetime import datetime
import tempfile

app = Flask(__name__)
CORS(app)

# Email configuration
SENDER_EMAIL = os.environ.get("SENDER_EMAIL")
SENDER_PASSWORD = os.environ.get("SENDER_PASSWORD")
SMTP_SERVER = os.environ.get("SMTP_SERVER", "smtp.gmail.com")
SMTP_PORT = int(os.environ.get("SMTP_PORT", "587"))


@app.route("/send-email", methods=["POST"])
def send_email():
    """
    Expected JSON payload:
    {
        "recipient_email": "user@example.com",
        "report_data": {...},     # REQUIRED (metadata + summary + findings)
        "target_url": "https://example.com",
        "include_pdf": true,      # handled client-side
        "include_json": true
    }
    """
    try:
        data = request.get_json()
        if not data:
            return jsonify({"error": "No data provided"}), 400

        recipient_email = data.get("recipient_email")
        report_data = data.get("report_data")
        target_url = data.get("target_url", "Unknown")
        include_pdf = bool(data.get("include_pdf", False))
        include_json = bool(data.get("include_json", False))

        if not recipient_email:
            return jsonify({"error": "Recipient email is required"}), 400

        if not include_pdf and not include_json:
            return jsonify({"error": "At least one format must be selected"}), 400

        if include_json and not report_data:
            return jsonify({"error": "JSON data missing"}), 400

        temp_files = []
        json_file = None

        timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")

        # ---------------------------
        # JSON attachment (server-side)
        # ---------------------------
        if include_json:
            json_file = os.path.join(
                tempfile.gettempdir(),
                f"security_report_{timestamp}.json"
            )
            with open(json_file, "w", encoding="utf-8") as f:
                json.dump(report_data, f, indent=2, ensure_ascii=False)

            temp_files.append(json_file)
            app.logger.info(f"Generated JSON at {json_file}")

        # ---------------------------
        # PDF handling (CLIENT-SIDE ONLY)
        # ---------------------------
        if include_pdf:
            app.logger.info(
                "PDF requested – handled client-side via browser print (no server PDF)"
            )

        # ---------------------------
        # Send email
        # ---------------------------
        success = send_report_email(
            recipient_email=recipient_email,
            pdf_file=None,          # IMPORTANT: no server PDF
            json_file=json_file,
            target_url=target_url,
            sender_email=SENDER_EMAIL,
            sender_password=SENDER_PASSWORD,
            smtp_server=SMTP_SERVER,
            smtp_port=SMTP_PORT
        )

        # Cleanup temp files
        for t in temp_files:
            try:
                if os.path.exists(t):
                    os.remove(t)
            except Exception:
                app.logger.warning(f"Could not delete temp file {t}")

        if success:
            return jsonify({
                "success": True,
                "message": f"Report sent to {recipient_email}"
            }), 200
        else:
            return jsonify({
                "success": False,
                "error": "Failed to send email (SMTP)"
            }), 500

    except Exception as e:
        app.logger.exception("Unhandled error in /send-email")
        return jsonify({"success": False, "error": str(e)}), 500


@app.route("/health", methods=["GET"])
def health_check():
    return jsonify({
        "status": "running",
        "service": "WebSecScan Email Server",
        "timestamp": datetime.now().isoformat()
    }), 200


@app.route("/", methods=["GET"])
def index():
    return """
    <html>
    <head>
      <title>WebSecScan Email Server</title>
      <style>
        body { font-family: Arial; max-width: 800px; margin: 40px auto; }
        code { background:#eee; padding:2px 6px; border-radius:4px; }
      </style>
    </head>
    <body>
      <h1>🛡️ WebSecScan Email Server</h1>
      <p>Status: <strong>Running</strong></p>

      <h3>Endpoints</h3>
      <ul>
        <li><code>POST /send-email</code></li>
        <li><code>GET /health</code></li>
      </ul>

      <h3>Notes</h3>
      <ul>
        <li>PDF is generated by the browser (not server)</li>
        <li>Server sends JSON attachment only</li>
        <li>No wkhtmltopdf required</li>
      </ul>
    </body>
    </html>
    """


def main():
    print("\n" + "=" * 60)
    print("🛡️  WebSecScan Email Server")
    print("=" * 60)

    if not SENDER_EMAIL or not SENDER_PASSWORD:
        print("\n⚠️  WARNING: Email credentials not configured")
    else:
        print(f"✓ Sender email: {SENDER_EMAIL}")
        print(f"✓ SMTP server: {SMTP_SERVER}:{SMTP_PORT}")

    print("\n🚀 Starting server on http://localhost:5000\n")
    app.run(host="0.0.0.0", port=5000, debug=False)


if __name__ == "__main__":
    main()