#optional_email.py
import os
import smtplib
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText
from email.mime.base import MIMEBase
from email import encoders
from datetime import datetime
from typing import Optional


# Default SMTP Configuration
DEFAULT_SMTP_CONFIG = {
    "smtp_server": "smtp.gmail.com",  
    "smtp_port": 587,                  
    "use_tls": True
}


def send_report_email(
    recipient_email: str,
    pdf_file: Optional[str] = None,
    json_file: Optional[str] = None,
    target_url: str = "Unknown",
    sender_email: Optional[str] = None,
    sender_password: Optional[str] = None,
    smtp_server: Optional[str] = None,
    smtp_port: Optional[int] = None,
    use_tls: bool = True
) -> bool:
    
    # Use default SMTP config if not provided
    if smtp_server is None:
        smtp_server = DEFAULT_SMTP_CONFIG["smtp_server"]
    if smtp_port is None:
        smtp_port = DEFAULT_SMTP_CONFIG["smtp_port"]
    
    # Validate inputs
    if not recipient_email:
        print("❌ Error: Recipient email address is required")
        return False
    
    if not pdf_file and not json_file:
        print("❌ Error: At least one file (PDF or JSON) must be provided")
        return False
    
    # Check if files exist
    if pdf_file and not os.path.exists(pdf_file):
        print(f"❌ Error: PDF file not found: {pdf_file}")
        return False
    
    if json_file and not os.path.exists(json_file):
        print(f"❌ Error: JSON file not found: {json_file}")
        return False
    
    # Get sender credentials if not provided
    if not sender_email:
        print("\n📧 Email Configuration")
        print("-" * 50)
        sender_email = input("Enter your email address: ").strip()
    
    if not sender_password:
        import getpass
        print("\nNote: For Gmail, use an App Password (not your regular password)")
        print("Generate at: https://myaccount.google.com/apppasswords")
        sender_password = getpass.getpass("Enter your email password/app password: ").strip()
    
    if not sender_email or not sender_password:
        print("❌ Error: Email credentials are required")
        return False
    
    try:
        # Create message
        msg = MIMEMultipart()
        msg['From'] = sender_email
        msg['To'] = recipient_email
        msg['Subject'] = f"WebSecScan Security Report - {target_url} - {datetime.now().strftime('%Y-%m-%d')}"
        
        # Email body
        body = f"""
Security Scan Report
{'=' * 60}

Target URL: {target_url}
Scan Date: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}

This email contains the security scan report for the above target.

Attachments:
"""
        
        if pdf_file:
            body += f"  • {os.path.basename(pdf_file)} - Visual report (PDF)\n"
        if json_file:
            body += f"  • {os.path.basename(json_file)} - Structured data (JSON)\n"
        
        body += """

Please review the findings and take appropriate action on any
security vulnerabilities identified.

---
Generated by WebSecScan
Web Security Misconfiguration Analyzer
"""
        
        msg.attach(MIMEText(body, 'plain'))
        
        # Attach PDF file if provided
        if pdf_file:
            try:
                with open(pdf_file, 'rb') as f:
                    part = MIMEBase('application', 'pdf')
                    part.set_payload(f.read())
                    encoders.encode_base64(part)
                    part.add_header(
                        'Content-Disposition',
                        f'attachment; filename={os.path.basename(pdf_file)}'
                    )
                    msg.attach(part)
                print(f"  ✓ Attached PDF: {os.path.basename(pdf_file)}")
            except Exception as e:
                print(f"  ✗ Failed to attach PDF: {e}")
                return False
        
        # Attach JSON file if provided
        if json_file:
            try:
                with open(json_file, 'rb') as f:
                    part = MIMEBase('application', 'json')
                    part.set_payload(f.read())
                    encoders.encode_base64(part)
                    part.add_header(
                        'Content-Disposition',
                        f'attachment; filename={os.path.basename(json_file)}'
                    )
                    msg.attach(part)
                print(f"  ✓ Attached JSON: {os.path.basename(json_file)}")
            except Exception as e:
                print(f"  ✗ Failed to attach JSON: {e}")
                return False
        
        # Connect to SMTP server and send email
        print(f"\n📤 Connecting to SMTP server: {smtp_server}:{smtp_port}")
        
        if use_tls:
            server = smtplib.SMTP(smtp_server, smtp_port)
            server.starttls()  # Enable TLS encryption
        else:
            server = smtplib.SMTP(smtp_server, smtp_port)
        
        print("  ✓ Connected")
        
        print("🔐 Authenticating...")
        server.login(sender_email, sender_password)
        print("  ✓ Authenticated")
        
        print(f"📧 Sending email to {recipient_email}...")
        server.send_message(msg)
        print("  ✓ Email sent successfully!")
        
        server.quit()
        
        return True
        
    except smtplib.SMTPAuthenticationError:
        print("\n❌ Authentication failed!")
        print("   For Gmail users:")
        print("   1. Enable 2-Step Verification in your Google Account")
        print("   2. Generate an App Password at: https://myaccount.google.com/apppasswords")
        print("   3. Use the App Password instead of your regular password")
        return False
        
    except smtplib.SMTPException as e:
        print(f"\n❌ SMTP error occurred: {e}")
        return False
        
    except Exception as e:
        print(f"\n❌ Failed to send email: {e}")
        return False


# Example usage and testing
if __name__ == "__main__":
    print("WebSecScan Email Module - Test Mode")
    print("=" * 50)
    
    test_recipient = input("Enter recipient email for test: ").strip()
    
    if test_recipient:
        print("\nNote: This is a test. Make sure you have test files ready.")
        pdf_test = input("Enter PDF file path (or press Enter to skip): ").strip()
        json_test = input("Enter JSON file path (or press Enter to skip): ").strip()
        
        if pdf_test or json_test:
            success = send_report_email(
                recipient_email=test_recipient,
                pdf_file=pdf_test if pdf_test else None,
                json_file=json_test if json_test else None,
                target_url="https://example.com"
            )
            
            if success:
                print("\n✅ Test email sent successfully!")
            else:
                print("\n❌ Test email failed!")
        else:
            print("\n❌ No files specified for attachment")
    else:
        print("\n❌ No recipient email provided")